### ISSUE TITLE
Token do bot exposto

### ISSUE THREAD

**Issue by ARJOM** [marcoslorhanbs/SWRDX-BOT#1]
No main.py é possível ver as informações do token do seu bot. O ideal é que essa informação esteja armazenada em uma variável de ambiente.

**Comment by marcoslorhanbs** [comment]
Valeu por avisar man. O discord me informou sobre, já foi alterado.

Em qua, 3 de jun de 2020 11:49, Antônio Ricart <notifications@github.com>
escreveu:
